.section __DATA,__ggml_metallib
.globl _ggml_metallib_start
_ggml_metallib_start:
.incbin "/Users/ernest.lee/Desktop/weftspun/3-interactor/motion-bricks-cpp/build-verify/ggml/src/ggml-metal/autogenerated/ggml-metal-embed.metal"
.globl _ggml_metallib_end
_ggml_metallib_end:
